#!/bin/bash
telnetvar=$(ss -tulpn | grep 21)

if [[ $telnetvar ]]
then
	if [[ -f dialupnoise.webm ]]
	then	
		firefox dialupnoise.webm
	else
		wget https://telnetnoise.s3.us-east-2.amazonaws.com/dialupnoise.webm
		firefox dialupnoise.webm
	fi
fi

